{
    "name": "Bader Custom",
    "version": "16.0.1.13.0",
    "category": "Other",
    "author": "Obertix",
    "website": "https://obertix.net",
    "license": "AGPL-3",
    "depends": [
        "account",
        "mis_builder",
        "product",
        "purchase",
        "repair",
        "report_csv",
        "report_xlsx",
        "sale",
        "stock",
        "web",
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/security.xml",
        "wizards/product_export_views.xml",
        "wizards/product_lot_export_views.xml",
        "wizards/product_pricelist_import.xml",
        "reports/layouts.xml",
        "reports/product_lot_export_report_views.xml",
        "reports/report_invoice_views.xml",
        "reports/report_purchase_views.xml",
        "reports/report_repair_views.xml",
        "reports/report_sale_views.xml",
        "reports/report_stock_views.xml",
        "views/product_pricelist_item_views.xml",
        "views/repair_order_views.xml",
    ],
    "assets": {
        "web.report_assets_common": ["bader_custom/static/src/css/custom.css"],
    },
}
